server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8080/rsa/publicKey' #配置RSA的公钥访问地址

  main:
    allow-bean-definition-overriding: true